echo "# Plan for Per-Tab Theme Customization and Wallpaper System"
echo "## 1. Types Update (\`src/types.ts\` and \`src/components/ThemeCustomizer.tsx\`)"
echo "Add new properties to \`UserCustomTheme\` interface and \`ThemeState\` for per-tab active colors, per-tab accent glows, and per-tab wallpapers."
echo "Need to support 5 tabs: HOME, REVISION_HUB, MY_ROUTINE, COMMUNITY_SUPPORT, PROFILE."
echo "Wallpapers can be base64 uploaded strings or URLs."
echo "## 2. Update \`ThemeCustomizer.tsx\` UI"
echo "Add sections for configuring these per-tab colors and wallpapers."
echo "Implement a file uploader that converts images to base64."
echo "Implement text inputs for direct URL inputs."
echo "## 3. Update \`StudentDashboard.tsx\` Logic"
echo "Dynamically get the correct colors and wallpapers depending on the current active tab."
echo "Ensure \`LESSON\` / \`NOTES\` views are exempted."
echo "## 4. Pre-commit instructions"
echo "Ensure proper testing, verification, review, and reflection are done."
